  spring.profiles.active=dev
hmdp:

  datasource:
    driver-class-name: ${HMDP_DATASOURCE_DRIVER_CLASS_NAME}
    url: jdbc:mysql://${HMDP_DATASOURCE_HOST}/${HMDP_DATASOURCE_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${HMDP_DATASOURCE_USERNAME}
    password: ${HMDP_DATASOURCE_PASSWORD}

  rabbitmq:
    host: ${HMDP_RABBITMQ_HOST:127.0.0.1}
    port: ${HMDP_RABBITMQ_PORT:5672}
    username: ${HMDP_RABBITMQ_USERNAME}
    password: ${HMDP_RABBITMQ_PASSWORD}
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: '/'
  redis:
    host: ${HMDP_REDIS_HOST:127.0.0.1}
    port: ${HMDP_REDIS_PORT:6379}
    password: ${HMDP_REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

